version: "3"
services:
        app:
                image: yash1600/spring-pet:v7
                container_name: app
                ports:
                        - 8080:8080
                environment:
                        - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
                        - OTEL_RESOURCE_ATTRIBUTES=service.name=app,compose_service=app
                        - OTEL_METRICS_EXPORTER=none
                        - SPRING_DATASOURCE_URL=jdbc:postgresql://db/compose-postgres
                        - SPRING_DATASOURCE_USERNAME=compose-postgres
                        - SPRING_DATASOURCE_PASSWORD=compose-postgres
                        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
                volumes:
                        - ./logs/application-Observability.log:/tmp/application-observability.log
                        
        db:
                image: 'postgres:13.1-alpine'
                container_name: db
                environment:
                        - POSTGRES_USER=compose-postgres
                        - POSTGRES_PASSWORD=compose-postgres
                volumes:
                        - user_data:/var/lib/postgresql
volumes:
        user_data:
                driver: local
